// Catálogo de técnicas por categoria.
// Edite à vontade: é só uma lista de strings. A ordem aqui é a ordem que aparece no app.
const CATALOGO = {
  'Finalizações': [
    'Armlock',
    'Armlock da montada',
    'Armlock da guarda',
    'Triângulo',
    'Triângulo de mão',
    'Kimura',
    'Americana',
    'Omoplata',
    'Mata-leão',
    'Estrangulamento cruzado (gola)',
    'Ezequiel',
    'Baseball choke',
    'Bow and arrow',
    'Relógio',
    'Guilhotina',
    'Anaconda',
    "D'Arce",
    'Katagatame',
    'Loop choke',
    'Norte-sul choke',
    'Chave de pé reta',
    'Chave de calcanhar (heel hook)',
    'Chave de joelho (kneebar)',
    'Toe hold',
    'Chave de panturrilha',
    'Mão de vaca',
    'Bíceps slicer',
    'Gogoplata',
  ],
  'Guardas e posições': [
    'Guarda fechada',
    'Meia-guarda',
    'Meia-guarda profunda',
    'Guarda Z (joelho escudo)',
    'Guarda aberta',
    'Guarda aranha',
    'Guarda laçada (lasso)',
    'Guarda De La Riva',
    'Guarda De La Riva invertida',
    'Guarda X',
    'Single leg X',
    'Guarda borboleta',
    'Guarda sentada',
    'Guarda lapela',
    'Guarda 50/50',
    'Guarda K',
    'Montada',
    'Pegada de costas',
    'Cem quilos',
    'Joelho na barriga',
    'Norte-sul',
    'Tartaruga',
  ],
  'Raspagens': [
    'Raspagem de meia-guarda',
    'Raspagem tesoura',
    'Raspagem de gancho (borboleta)',
    'Raspagem de flor (pêndulo)',
    'Hip bump',
    'Raspagem De La Riva',
    'Raspagem de guarda X',
    'Raspagem de aranha',
    'Raspagem de laçada',
    'Raspagem de lapela',
    'Raspagem de guarda sentada',
    'Raspagem de 50/50',
    'Raspagem tornado',
    'Raspagem da meia-guarda profunda',
  ],
  'Passagens': [
    'Passagem toreando',
    'Passagem de joelho (knee cut)',
    'Leg drag',
    'Passagem por baixo (double under)',
    'Passagem over-under',
    'Passagem stack',
    'Passagem de meia-guarda',
    'Passagem smash',
    'X-pass',
    'Long step',
    'Passagem body lock',
    'Passagem em pé',
    'Passagem de De La Riva',
  ],
  'Quedas': [
    'Single leg',
    'Double leg',
    'Osoto gari',
    'Ouchi gari',
    'Kouchi gari',
    'Seoi nage',
    'Uchi mata',
    'Harai goshi',
    'Tomoe nage',
    'Sumi gaeshi',
    'Ankle pick',
    'Arm drag',
    'Snap down',
    'Puxada para a guarda',
  ],
  'Escapes e defesas': [
    'Saída da montada (upa)',
    'Saída da montada (elbow escape)',
    'Saída do cem quilos',
    'Saída das costas',
    'Saída do joelho na barriga',
    'Saída do norte-sul',
    'Saída da tartaruga',
    'Reposição de guarda',
    'Granby roll',
    'Defesa de triângulo',
    'Defesa de armlock',
    'Defesa de mata-leão',
    'Defesa de guilhotina',
    'Defesa de kimura',
    'Defesa de chave de pé',
  ],
};
